development:
  adapter: postgresql
  encoding: unicode
  database: jaime_development
  pool: 5
  username: admin

test:
  adapter: postgresql
  encoding: unicode
  database: jaime_test
  pool: 5
  username: admin
