# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c0b45937825d216fe0d3f5c82ba96bf60d72e14ddc57e0db6443922d5e35d71bbe8818aea62556990adea552aa2a1ce65fd439ba0ff035a03f71433fcb23064

test:
  secret_key_base: 5b5a98c438895c154d9ea814c002f7ce921586080920e188f4b93f376069fc33dc577f5c90a9e7446ee1be6cb6830b50efcd8e3f79b79f999b318215df17b4ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
